package com.mediacleaner.DataModels.Emby

data class MediaSource(
        val Protocol: String?,
        val Id: String?,
        val Path: String?,
        val Type: String?,
        val Container: String?,
        val Name: String?,
        val IsRemote: Boolean?,
        val ETag: String?,
        val RunTimeTicks: Any?,
        val ReadAtNativeFramerate: Boolean?,
        val IgnoreDts: Boolean?,
        val IgnoreIndex: Boolean?,
        val GenPtsInput: Boolean?,
        val SupportsTranscoding: Boolean?,
        val SupportsDirectStream: Boolean?,
        val SupportsDirectPlay: Boolean?,
        val IsInfiniteStream: Boolean?,
        val RequiresOpening: Boolean?,
        val RequiresClosing: Boolean?,
        val SupportsProbing: Boolean?,
        val EnableMpDecimate: Boolean?,
        val RequiresLooping: Boolean?,
        val VideoType: String?,
        val MediaStreams: List<Any>?,
        val Formats: List<Any>?,
        val Bitrate: Int?,
        val DefaultAudioStreamIndex: Int?,
        val DefaultSubtitleStreamIndex: Int?
)