package com.mediacleaner.DataModels.Emby

data class Policy(
    val IsAdministrator: Boolean?,
    val IsHidden: Boolean?,
    val IsDisabled: Boolean?,
    val BlockedTags: List<Any>?,
    val EnableUserPreferenceAccess: Boolean?,
    val AccessSchedules: List<Any>?,
    val BlockUnratedItems: List<Any>?,
    val EnableRemoteControlOfOtherUsers: Boolean?,
    val EnableSharedDeviceControl: Boolean?,
    val EnableLiveTvManagement: Boolean?,
    val EnableLiveTvAccess: Boolean?,
    val EnableMediaPlayback: Boolean?,
    val EnableAudioPlaybackTranscoding: Boolean?,
    val EnableVideoPlaybackTranscoding: Boolean?,
    val EnablePlaybackRemuxing: Boolean?,
    val EnableContentDeletion: Boolean,
    val EnableContentDownloading: Boolean?,
    val EnableSyncTranscoding: Boolean?,
    val EnabledDevices: List<Any>?,
    val EnableAllDevices: Boolean?,
    val EnabledChannels: List<Any>?,
    val EnableAllChannels: Boolean?,
    val EnabledFolders: List<Any>?,
    val EnableAllFolders: Boolean?,
    val InvalidLoginAttemptCount: Int?,
    val EnablePublicSharing: Boolean?
)