package com.mediacleaner.DataModels.Emby

data class UserItem(
        val Name: String,
        val ServerId: String?,
        val Id: String?,
        val HasSubtitles: Boolean?,
        val Container: String?,
        val PremiereDate: String?,
        val DateCreated: String,
        val MediaSources: List<MediaSource?> = emptyList(),
        val CommunityRating: Double?,
        val RunTimeTicks: Any?,
        val ProductionYear: Int?,
        val IndexNumber: Int,
        val ParentIndexNumber: Int?,
        val IsFolder: Boolean?,
        val Type: String?,
        val ParentLogoItemId: String?,
        val ParentBackdropItemId: String?,
        val ParentBackdropImageTags: List<String>?,
        val LocalTrailerCount: Int?,
        val UserData: UserData,
        val SeriesName: String,
        val SeriesId: String?,
        val SeasonId: String?,
        val SeriesPrimaryImageTag: String?,
        val SeasonName: String?,
        val VideoType: String?,
        val ImageTags: ImageTags? = null,
        val BackdropImageTags: List<Any>?,
        val ParentLogoImageTag: String?,
        val ParentThumbItemId: String?,
        val ParentThumbImageTag: String?,
        val LocationType: String?,
        val MediaType: String?,
        val IsHD: Boolean
)